packer {
  required_plugins {
    proxmox = {
      version = ">= 1.2.3"
      source  = "github.com/hashicorp/proxmox"
    }
  }
}

variable "node" {
  type    = string
}

variable "iso_pool" {
  type    = string
  default = "local"
}

variable "storage_pool" {
  type    = string
  default = "local-lvm"
}

variable "proxmox_url" {
  type    = string
  default = "https://proxmox.hostname.tld:8006"
}

variable "proxmox_username" {
  type    = string
  default = "root@pam"
}

variable "proxmox_password" {
  type    = string
}

variable "template_description" {
  type    = string
  default = "Ubuntu 24.04 LTS Template"
}

variable "template_name" {
  type    = string
  default = "Ubuntu-24.04-LTS-Template"
}

variable "iso_file" {
  type = string
  default = "local:iso/ubuntu-24.04.3-live-server-amd64.iso"
}

variable "ssh_password" {
  type = string
  default = "changeme4realz"
}

variable "ssh_username" {
  type = string
  default = "ubuntu"
}

source "proxmox-iso" "autogenerated_1" {
  boot_command = ["c", "linux /casper/vmlinuz -- autoinstall ds='nocloud-net;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/'", "<enter><wait><wait>", "initrd /casper/initrd", "<enter><wait><wait>", "boot<enter>"]
  boot_wait    = "10s"
  cores        = "2"
  disks {
    disk_size         = "8G"
    storage_pool      = "${var.storage_pool}"
    type              = "scsi"
  }
  insecure_skip_tls_verify = true
  memory                   = "2048"
  network_adapters {
    bridge = "vmbr0"
  }
  boot_iso {
    type = "scsi"
    iso_file = "${var.iso_file}"
    unmount = true
    iso_checksum = "sha256:c3514bf0056180d09376462a7a1b4f213c1d6e8ea67fae5c25099c6fd3d8274b"
  }
  node                 = "${var.node}"
  os                   = "l26"
  username             = "${var.proxmox_username}"
  password             = "${var.proxmox_password}"
  proxmox_url          = "${var.proxmox_url}"
  scsi_controller      = "virtio-scsi-single"
  ssh_port             = 22
  ssh_timeout          = "30m"
  template_description = "${var.template_description}"
  template_name        = "${var.template_name}"
  ssh_username         = "${var.ssh_username}"
  ssh_password         = "${var.ssh_password}"
}

build {
  sources = ["source.proxmox-iso.autogenerated_1"]

  provisioner "shell" {
    inline = ["while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 1; done", "sudo rm -f /etc/cloud/cloud.cfg.d/99-installer.cfg", "sudo cloud-init clean", "sudo passwd -d ${var.ssh_username}"]
  }
}
