packer {
  required_plugins {
    proxmox = {
      version = ">= 1.2.3"
      source  = "github.com/hashicorp/proxmox"
    }
  }
}

variable "proxmox_url" {
  type    = string
  default = "https://proxmox.hostname.tld:8006"
}

source "proxmox-clone" "vm" {
  clone_vm = "ubuntu-24-lts-cloudimg-template"
  cd_files = ["./ubuntu2404/meta-data", "./ubuntu2404/user-data"]
  cd_label = "cidata"
  proxmox_url = var.proxmox_url
}

# variable "node" {
#   type    = string
# }

# variable "iso_pool" {
#   type    = string
#   default = "local"
# }

# variable "storage_pool" {
#   type    = string
#   default = "local-lvm"
# }

# variable "proxmox_username" {
#   type    = string
#   default = "root@pam"
# }

# variable "proxmox_password" {
#   type    = string
# }

# variable "template_description" {
#   type    = string
#   default = "Ubuntu 24.04 LTS Template"
# }

# variable "template_name" {
#   type    = string
#   default = "Ubuntu-24.04-LTS-Template"
# }

# variable "iso_file" {
#   type = string
#   default = "local:iso/ubuntu-24.04.3-live-server-amd64.iso"
# }

# variable "iso_file_checksum" {
#   type = string
#   default = "sha256:c3514bf0056180d09376462a7a1b4f213c1d6e8ea67fae5c25099c6fd3d8274b"
# }

# source "proxmox-iso" "autogenerated_1" {
#   boot_command = [
#     "c", 
#     "linux /casper/vmlinuz -- autoinstall ds='nocloud-net;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/'",
#     "<enter><wait><wait>",
#     "initrd /casper/initrd",
#     "<enter><wait><wait>",
#     "boot<enter>"
#   ]

#   # efi_config {
#   #   efi_format        = "raw"
#   #   efi_storage_pool  = "local-lvm"
#   #   efi_type          = "4m"
#   #   pre_enrolled_keys = true
#   # }

#   boot_wait                = "10s"
#   cores                    = "2"
#   insecure_skip_tls_verify = true
#   memory                   = "4096"
#   # bios                     = "omvf"
#   scsi_controller          = "virtio-scsi-single"

#   disks {
#     disk_size    = "20G"
#     storage_pool = "${var.storage_pool}"
#     #format       = "raw"
#     type         = "scsi"
#   }
  
#   network_adapters {
#     bridge = "vmbr0"
#   }
  
#   boot_iso {
#     type         = "scsi"
#     unmount      = true
#     iso_file     = "${var.iso_file}"
#     iso_checksum = "${var.iso_file_checksum}"
#   }

#   node                 = "${var.node}"
#   os                   = "l26"
#   username             = "${var.proxmox_username}"
#   password             = "${var.proxmox_password}"
#   proxmox_url          = "${var.proxmox_url}"
#   ssh_port             = 22
#   ssh_timeout          = "30m"
#   template_name        = "${var.template_name}"
#   template_description = "${var.template_description}"
#   ssh_username         = "ubuntu"
#   ssh_password         = "changeme4realz"
#   qemu_agent           = true
#   # cloud_init_disk_type = "scsi"

#   # additional_iso_files {
#   #   type = "scsi"
#   #   # Paths to the files that will be put on the CD
#   #   cd_files = ["./ubuntu2404/meta-data", "./ubuntu2404/user-data" ]
#   #   # The label for the CD, commonly 'cidata' for cloud-init
#   #   cd_label = "cidata"
#   #   # Specify the storage pool where the ISO will be created
#   #   iso_storage_pool = "local"
#   #   # Set to true if you want the CD to be unmounted automatically after the build
#   #   unmount = true
#   # }
# }

# build {
#   sources = ["source.proxmox-iso.autogenerated_1"]

#   provisioner "shell" {
#     inline = ["while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 1; done", "sudo rm -f /etc/cloud/cloud.cfg.d/99-installer.cfg", "sudo cloud-init clean", "sudo passwd -d ubuntu"]
#   }
# }
