apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-vip-config
  namespace: kube-system
data:
  kubevip.yaml: |
    apiVersion: kube-vip.io/v1
    kind: Config
    address: 192.168.68.100
    interface: eth0
    services:
      - type: ClusterIP
        arp: true
        port: 6443
        protocol: tcp
        ingress:
          - 192.168.68.100
