apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-vip-configmap.yaml
  - kube-vip-daemonset.yaml
namespace: kube-system
images:
  - name: plndr/kube-vip
    newTag: v0.5.5
configMapGenerator:
  - name: kube-vip-config
    behavior: merge
    literals:
      - "vip=192.168.68."
      - "interface=eth0"
      - "arp=true"
      - "bgp=false"
      - "vip_cidr=32"
